---
name: ğŸ†˜ Help wanted

on:
  issues:
    types: [opened]

jobs:
  issue:
    name: ğŸ” Get inputs
    if: ${{ contains(github.event.issue.labels.*.name, 'help wanted') }}
    runs-on: ubuntu-latest
    outputs:
      helpneededwith: ${{ steps.inputs.outputs.help_needed_with }}
    steps:
      - name: ğŸ“¥ Get inputs
        id: inputs
        uses: drdonoso/issueform-get-inputs@main
        with:
          body-input: ${{ github.event.issue.body }}
    
  call-workflow:
    needs: issue
    runs-on: ubuntu-latest
    name: ğŸš€ Run 
    steps: 
      - name: ğŸš€ Run
        shell: bash
        run: |
          echo "Running the workflow"
          echo "Help needed with: ${{ needs.issue.outputs.helpneededwith }}"

  close:
    needs: call-workflow
    name: âœ”ï¸ Close issue
    runs-on: ubuntu-22.04
    steps:
      - name: âœï¸ Close issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '### Answer here:',
            });